/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_BACKUP_PB_H_INCLUDED
#define PB_BACKUP_PB_H_INCLUDED
#include <pb/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Config {
    uint64_t version;
    pb_callback_t content;
    pb_callback_t md5;
} Config;

typedef struct _Instance {
    pb_callback_t host;
    int32_t port;
    int32_t weight;
    pb_callback_t cluster;
} Instance;

typedef struct _Service {
    uint64_t version;
    pb_callback_t instances;
} Service;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Config_init_default                      {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Instance_init_default                    {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define Service_init_default                     {0, {{NULL}, NULL}}
#define Config_init_zero                         {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Instance_init_zero                       {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define Service_init_zero                        {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Config_version_tag                       1
#define Config_content_tag                       2
#define Config_md5_tag                           3
#define Instance_host_tag                        1
#define Instance_port_tag                        2
#define Instance_weight_tag                      3
#define Instance_cluster_tag                     4
#define Service_version_tag                      1
#define Service_instances_tag                    2

/* Struct field encoding specification for nanopb */
#define Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   version,           1) \
X(a, CALLBACK, SINGULAR, STRING,   content,           2) \
X(a, CALLBACK, SINGULAR, STRING,   md5,               3)
#define Config_CALLBACK pb_default_field_callback
#define Config_DEFAULT NULL

#define Instance_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   host,              1) \
X(a, STATIC,   SINGULAR, INT32,    port,              2) \
X(a, STATIC,   SINGULAR, INT32,    weight,            3) \
X(a, CALLBACK, SINGULAR, STRING,   cluster,           4)
#define Instance_CALLBACK pb_default_field_callback
#define Instance_DEFAULT NULL

#define Service_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   version,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  instances,         2)
#define Service_CALLBACK pb_default_field_callback
#define Service_DEFAULT NULL
#define Service_instances_MSGTYPE Instance

extern const pb_msgdesc_t Config_msg;
extern const pb_msgdesc_t Instance_msg;
extern const pb_msgdesc_t Service_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Config_fields &Config_msg
#define Instance_fields &Instance_msg
#define Service_fields &Service_msg

/* Maximum encoded size of messages (where known) */
/* Config_size depends on runtime parameters */
/* Instance_size depends on runtime parameters */
/* Service_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
