/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "backup.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Config, Config, AUTO)


PB_BIND(Instance, Instance, AUTO)


PB_BIND(Service, Service, AUTO)



