/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "nacos_grpc_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Any, Any, AUTO)


PB_BIND(Metadata, Metadata, AUTO)


PB_BIND(Metadata_HeadersEntry, Metadata_HeadersEntry, AUTO)


PB_BIND(Payload, Payload, AUTO)



