/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_NACOS_GRPC_SERVICE_PB_H_INCLUDED
#define PB_NACOS_GRPC_SERVICE_PB_H_INCLUDED
#include <pb/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Any {
    pb_callback_t type_url;
    pb_callback_t value;
} Any;

typedef struct _Metadata {
    pb_callback_t type;
    pb_callback_t headers;
    pb_callback_t clientIp;
} Metadata;

typedef struct _Metadata_HeadersEntry {
    pb_callback_t key;
    pb_callback_t value;
} Metadata_HeadersEntry;

typedef struct _Payload {
    bool has_metadata;
    Metadata metadata;
    bool has_body;
    Any body;
} Payload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Any_init_default                         {{{NULL}, NULL}, {{NULL}, NULL}}
#define Metadata_init_default                    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Metadata_HeadersEntry_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define Payload_init_default                     {false, Metadata_init_default, false, Any_init_default}
#define Any_init_zero                            {{{NULL}, NULL}, {{NULL}, NULL}}
#define Metadata_init_zero                       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Metadata_HeadersEntry_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define Payload_init_zero                        {false, Metadata_init_zero, false, Any_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Any_type_url_tag                         1
#define Any_value_tag                            2
#define Metadata_type_tag                        3
#define Metadata_headers_tag                     7
#define Metadata_clientIp_tag                    8
#define Metadata_HeadersEntry_key_tag            1
#define Metadata_HeadersEntry_value_tag          2
#define Payload_metadata_tag                     2
#define Payload_body_tag                         3

/* Struct field encoding specification for nanopb */
#define Any_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   type_url,          1) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             2)
#define Any_CALLBACK pb_default_field_callback
#define Any_DEFAULT NULL

#define Metadata_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   type,              3) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,           7) \
X(a, CALLBACK, SINGULAR, STRING,   clientIp,          8)
#define Metadata_CALLBACK pb_default_field_callback
#define Metadata_DEFAULT NULL
#define Metadata_headers_MSGTYPE Metadata_HeadersEntry

#define Metadata_HeadersEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define Metadata_HeadersEntry_CALLBACK pb_default_field_callback
#define Metadata_HeadersEntry_DEFAULT NULL

#define Payload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define Payload_CALLBACK NULL
#define Payload_DEFAULT NULL
#define Payload_metadata_MSGTYPE Metadata
#define Payload_body_MSGTYPE Any

extern const pb_msgdesc_t Any_msg;
extern const pb_msgdesc_t Metadata_msg;
extern const pb_msgdesc_t Metadata_HeadersEntry_msg;
extern const pb_msgdesc_t Payload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Any_fields &Any_msg
#define Metadata_fields &Metadata_msg
#define Metadata_HeadersEntry_fields &Metadata_HeadersEntry_msg
#define Payload_fields &Payload_msg

/* Maximum encoded size of messages (where known) */
/* Any_size depends on runtime parameters */
/* Metadata_size depends on runtime parameters */
/* Metadata_HeadersEntry_size depends on runtime parameters */
/* Payload_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
